language: objective-c
osx_image: xcode8.1

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xctool clean build -project BGStatePicker.xcodeproj -scheme BGStatePicker -sdk iphonesimulator
- xctool test -project BGStatePicker.xcodeproj -scheme BGStatePicker -sdk iphonesimulator
